Feature/sort by rating or name
El-Duckster/EscapeRoom-grupp2 pull request #104
Opened 2024-12-09 18:29 UTC by MagnusTerak

In this PR i've added the feature to sort the displaying challenges cards.

**They can sort in the following way:** 

Name (A-Ö)
Name (Ö-A)
Rating - Highest to lowest
Rating - Lowest to highest

Previous code that has been edited is the executeSearch function

[Image fullpage]
![sortbig](https://github.com/user-attachments/assets/bd347529-c8f1-4434-b976-21b6c7ff4ae3)

[Image dropdown menu]
![sortcloseup](https://github.com/user-attachments/assets/983520da-9d7c-450d-9148-6134793da685)

2024-12-09 19:18 UTC, MagnusTerak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sortera rum på rating eller namn](https://trello.com/c/K37mreSe/10-sortera-rum-p%C3%A5-rating-eller-namn)

2024-12-09 20:53 UTC, Deansie reviewed
The sorting menu looks really good, well done! However, I wonder if we should perhaps stick with the language of our HTML document, so instead of A-Ö it should say A-Z.

After selecting a sorting option, when you click on any other filtering options, the sorting from your menu is reset. It would be nice if the sorting from your menu persisted even after other options are chosen.

2024-12-10 17:16 UTC, El-Duckster requested changes

2024-12-10 17:44 UTC, El-Duckster requested changes

2024-12-10 17:44 UTC, El-Duckster commented on src/js/challengeClass.js
> +    challengeDescription.textContent = this.description;
here too this will overrwritte the new changes.

2024-12-10 17:44 UTC, El-Duckster commented on src/js/challengeClass.js
> -import {truncateText} from './utilities/truncateText.js';
here :)

2024-12-10 19:58 UTC, MagnusTerak commented
This PR & Branch has gotten backtracked due to merges, we've decided to close this and delete the branch (New branch & PR with correct version has been created)

2024-12-10 19:58 UTC, closed without merging