Modul step 2 booking
El-Duckster/EscapeRoom-grupp2 pull request #59
Opened 2024-11-16 17:27 UTC by Dusknery

2024-11-16 19:56 UTC, El-Duckster commented
> added the same html for modul step 2 to challenges.html as in index.html

bra jobbat! 

Kan du gärna åtgärda dessa problem innan vi mergear ändringarna till main? Tack på förhand! 😊
![image](https://github.com/user-attachments/assets/1a3fd57b-a38d-4fa7-a2ef-a8a662b02588)

2024-11-17 23:25 UTC, El-Duckster requested changes

2024-11-26 17:09 UTC, Fagerdahl approved these changes
Nice work Elena & Linnea, I see a good separation of concerns and readable code. I had to look these ones up:
const isValidTime = (time) => /^\d{2}:\d{2}$/.test(time);  
 AND else if (!/^[a-zA-Z\s]{2,}$/.test(trimmedName))  :-D  
 Your naming conventions made it easy to understand what they do and that is great!
Your regex function to validate the email is next level and something new I have learned thanks to you! Well done. 

Also, I am a fan of "undantagshantering", so the only constructive feedback I can give is an if statement for wrong inputs in email. BUT Regex should cover the most complex inputs so don`t you think about it now :-) I absolutely approve this to be merged into main!

2024-11-26 18:55 UTC, Kirill9m approved these changes
Amazing work! The code is well written and well structured!
I see that you’re planning to integrate the code with Ronja soon! I think you’re doing an excellent job!

I checked the couple of test cases(code): 

- Correctly validates the entered email.
- Verifies the username.
- Collects information about available time and provides results
- Accurately provides the correct number of participants
- Finds the challenge by id
- Handles bookings by passing an object to the createReservation function and converting it into a JSON string

It’s fantastic that you wrote tests; this greatly simplifies data validation.

2024-11-27 10:37 UTC, El-Duckster approved these changes

2024-11-27 10:37 UTC, merged